import { DTOPartnerProduct } from "./DTOPartnerProduct.dto";

export class DTOProductPriceRequest extends DTOPartnerProduct{
    StatusDescription:string = ''
    PartnerID:string = ''
    PartnerName:string = ''
    COProduct: number = null
    VNName: string = ''
    JPName: string = ''
    ENName: string = ''
    BaseBarcode: string = ''
    Remark: string = ''
    TypeDataName: string = ''
    CurrentCOPartner: number = null
    Origin: number = null
    TaxCode: string = ""
    TaxName: string = ""
    TaxID: number = null
    MinQuantity: number = 0
    BaseUnit: number = null
    BuyerUnit: number = null
    BaseUnitL: number = null
    BaseUnitW: number = null
    BaseUnitH: number = null
    BaseUnitWeight: number = null
    InnerL: number = null
    InnerW: number = null
    InnerH: number = null
    InnerWeight: number = null
    InnerBase: number = null
    CartonL: number = null
    CartonW: number = null
    CartonH: number = null
    CartonWeight: number = null
    CartonBase: number = null
    PalletL: number = null
    PalletW: number = null
    PalletH: number = null
    PalletWeight: number = null
    PackageL: number = null
    PackageW: number = null
    PackageH: number = null
    PackageWeight: number = null
    PalletBase: number =null
    GroupID: number = null
    GroupID1: number = null
    GroupID2: number = null
    GroupID3: number = null
    GroupID4: number = null
    GroupName5: string = ''
    GroupName4: string = ''
    WebExpiredDate: string = ''
    DateDuration: number
    VNSpec: string = ''
    VATIn: number = 0
    IsDate: boolean = false
    CurrencyIn: number = null
    CommercialTerm: number = null
    VATOut: number = 0
    CurrencyOut: number = null
    Margin: number = 0
    QtyMore: number = 0
    QtyMonthSale: number = 0
    AmountMonthSale: number = 0
    QtyFirstOrder: number = 0
    MarginAmount: number = 0
    StoreFrom:Date | string = '' 
    StoreTo: Date | string = '' 
    WithoutConfig: string = ''
    FirstPO: string = ''
    POFrom: Date | string = '' 
    POTo: Date | string = '' 
    AvgPrice: number = 0
    CurrencyAvg: number = null
    Shipper: number = null
    MakerName: string = ''
    ENMaterial: string = ''
}
