export class EnumWebHachi {    
    static GetCurrentCart: string 
    static UpdateCart: string 
    static CheckProductStock: string 
    static DeleteCartDetail: string 
    static AddCart: string 
    static AddCoupon: string 
    static DeleteCoupon: string 
    static GetPayments: string 
    static PaymentCart: string 
    static GetOrderGifts: string
    static UpdateCartGift: string
    static GetProvinces: string
    static GetDistricts: string
    static GetWards: string
    static ChangeCartDelivery: string
    static GetAllDelivery: string
    static RemoveDelivery: string
    static UpdateDelivery: string
    static GetDelivery: string
    static GetListProduct: string
    static GetProductByBarcode: string
    static GetListGenOrder: string
    static DeleteGenOrder: string
    static AssignCartStaff: string
    static SynOrder: string
    static GetCardByStaff: string
    static getuserbyphone: string
}